name: peniremit
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  go_router: ^12.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.0
  iconify_flutter: ^0.0.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  internet_connection_checker: ^0.0.1+4
  intl: ^0.18.0
  nb_utils: ^6.0.6
  otp_text_field: ^1.1.3
  path_provider: ^2.0.13
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^3.0.1
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  qr: ^3.0.1
  responsive_framework: ^1.1.1
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  sized_context: ^1.0.0+4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/ads/

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Light.ttf
          weight: 200
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 500
        - asset: fonts/Lexend-Medium.ttf
          weight: 600
        - asset: fonts/Lexend-Bold.ttf
          weight: 700

    - family: NotoSerifJP
      fonts:
        - asset: fonts/NotoSerifJP-Regular.otf
          weight: 400

    - family: Peniremit
      fonts:
        - asset: fonts/peniremit.ttf
