import 'package:flutter/widgets.dart';

class PeniremitIcon {
  PeniremitIcon._();

  static const _kFontFam = 'Peniremit';
  static const String? _kFontPkg = null;

    static const IconData profile2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData betting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData naira = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData church = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribution_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airtime = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offertory = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donation = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prayer = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vousher = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1000002803 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refer = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addOutline = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdrawInner = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdrawOuter = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mass = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fundraising = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tithe = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collection = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harvest = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thanksgiving = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chip = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfcRight = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfcLeft = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData launching = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribution = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData welfare = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squareScan = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity2 = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
